Fix logic

diff --git a/.github/workflows/testing-release.yml b/.github/workflows/testing-release.yml
--- a/.github/workflows/testing-release.yml
+++ b/.github/workflows/testing-release.yml
@@ -62,9 +62,10 @@ jobs:
       - name: Check if tag ${{ inputs.release_version }} already exists. Exit pipeline if tag already exist.
         if: ${{ inputs.perform_release }}
         run: |
-          if [ $( git ls-remote --exit-code --tags origin '${{ inputs.release_version }}' ) ]; then
-            echo "FAILURE: Tag ${{ inputs.release_version}} already exists!" ; exit 1
-          fi
+          git ls-remote --exit-code --tags origin '${{ inputs.release_version }}' \
+            && ( echo "FAILURE: Tag ${{ inputs.release_version}} already exists!" ; exit 1 ) \
+            || echo "OK: Tag ${{ inputs.release_version}} does not exists. Proceeding release workflow."
+
 
   build:
     runs-on: ubuntu-24.04
