fix spacing

diff --git a/.github/workflows/testing-release.yml b/.github/workflows/testing-release.yml
--- a/.github/workflows/testing-release.yml
+++ b/.github/workflows/testing-release.yml
@@ -70,7 +70,7 @@ jobs:
 
       - name: Check if tag ${{ inputs.release_version }} already exists. Exit pipeline if tag already exist.
         run: |
-          git ls-remote --exit-code --tags origin ${{ inputs.release_version }} && ( echo "FAIL:Tag ${{ inputs.release_version}} already exists!" ; exit 1 )
+          git ls-remote --exit-code --tags origin ${{ inputs.release_version }} && ( echo "FAILURE: Tag ${{ inputs.release_version}} already exists!" ; exit 1 )
           
       - name: Debug content of current dir
         run: |
